---
#########################################
#################CentOS##################
#########################################
- name: restart iptables
  service: name=iptables state=reloaded

- name: restart httpd
  service: name=httpd state=restarted
#########################################
################Debian###################
#########################################
- name: restart apache
  service: name=apache2 state=restarted

- name: reload apache
  service: name=apache2 state=reloaded
